### ISSUE TITLE
Mandelbrot OpenCL test in gpuMagic

### ISSUE THREAD

**Issue by tomwenseleers** [Jiefei-Wang/gpuMagic#5]
Thanks for the nice package!
As a test case, I was interested to check how fast a Mandelbrot fractal would calculate using OpenCL & gpuMagic.
This was to compare with my own Rcpp+OpenMP CPU only version (including a SIMD version):
[https://github.com/tomwenseleers/mandelExplorer/blob/main/src/mandelRcpp.cpp](https://github.com/tomwenseleers/mandelExplorer/blob/main/src/mandelRcpp.cpp)
[https://github.com/tomwenseleers/mandelExplorer](https://github.com/tomwenseleers/mandelExplorer)

Based on the OpenCL code I found here, [https://www.polarnick.com/blogs/other/cpu/gpu/sse/opencl/openmp/2016/10/01/mandelbrot-set-sse-opencl.html](https://www.polarnick.com/blogs/other/cpu/gpu/sse/opencl/openmp/2016/10/01/mandelbrot-set-sse-opencl.html)
I tried :

```
# Set device & get default options
library(gpuMagic)

# getDeviceList()
setDevice(1)

options=kernel.getOption()

# define Mandelbrot OpenCL code
code='
kernel void mandelbrotOpenCL(global float fromX, global float toX, 
                             global float fromY, global float toY,
                             global int width, global int height,
                             global int maxiter,
                             global int* res) {
    int px = get_global_id(0);
    int py = get_global_id(1);
    if (px >= width || py >= height) return;

    float x0 = fromX + px * (toX - fromX) / width;
    float y0 = fromY + py * (toY - fromY) / height;

    int iteration;
    float x = 0.0f;
    float y = 0.0f;
    for (iteration = 0; iteration < maxiter; iteration++) {
        float xn = x * x - y * y + x0;
        y = 2 * x * y + y0;
        x = xn;
        if (x * x + y * y > 4.0) {
            break;
        }
    }
    res[width * py + px] = iteration;
}
}
}
'

# Create data in R
fromX = -0.7660326
toX = -0.7660326
fromY = 0.1008622
toY = 0.1008622
width = 640L
height = 640L
maxiter = 500L;
res = vector('integer', length=width*height)

# Send the data to GPU
fromX_dev = gpuMatrix(fromX, type='float')
toX_dev = gpuMatrix(toX, type='float')
fromY_dev = gpuMatrix(fromY, type='float')
toY_dev = gpuMatrix(toY, type='float')
width_dev = gpuMatrix(width, type='int')
height_dev = gpuMatrix(height, type='int')
maxiter_dev = gpuMatrix(maxiter, type='int')
# Create an empty data matrix in GPU
res_dev = gpuMatrix(res, type='int')
# Run the GPU function with n threads, each thread computes one column addition
n = 200 # nr of threads to use
.kernel(src = code, 
        kernel='mandelbrotOpenCL',
        parms=list(fromX_dev, toX_dev,
                   fromY_dev, toY_dev,
                   width_dev, height_dev,
                   maxiter_dev, 
                   res_dev),
        .globalThreadNum = n,
        .options = options)
if(!is.null(res_dev)){
  #Retrieve the data
  res_dev=download(res_dev)
  res=as.matrix(res_dev, ncol=width)
}
```

But the .kernel call returns
```
Error in .kernel(src = code, kernel = "mandelbrotOpenCL", parms = list(fromX_dev,  : 
  Fail to build program: -11
<kernel>:34:43: error: parameter may not be qualified with an address space
kernel void mandelbrotOpenCL(global float fromX, global float toX, 
                                          ^
<kernel>:34:63: error: parameter may not be qualified with an address space
kernel void mandelbrotOpenCL(global float fromX, global float toX, 
                                                              ^
<kernel>:35:43: error: parameter may not be qualified with an address space
                             global float fromY, global float toY,
                                          ^
<kernel>:35:63: error: parameter may not be qualified with an address space
                             global float fromY, global float toY,
                                                              ^
<kernel>:36:41: error: parameter may not be qualified with an address space
                             global int width, global int height,
```

Do you see by any chance what I am doing wrong?
Also, I was wondering what is the correct way to pass vectors and scalars? And constant scalars, like maxiter in this case, which I would like to be a const? Right now everything would seem to be passed as matrices, which somehow doesn't feel right...

(I should say this is the very first OpenCL program I try to write, so this may be something very obvious & stupid on my side)

PS I saw another Mandelbrot OpenCL implementation here, [https://github.com/benhiller/opencl-mandelbrot/blob/master/mandelbrot.cl](https://github.com/benhiller/opencl-mandelbrot/blob/master/mandelbrot.cl), but the above should probably be OK...

PS2 Intel also features the following OpenCL Mandelbrot implementation at [https://www.intel.com/content/www/us/en/support/programmable/support-resources/design-examples/horizontal/mandelbrot.html](https://www.intel.com/content/www/us/en/support/programmable/support-resources/design-examples/horizontal/mandelbrot.html), not sure which one would be preferrable :

```
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
// Amount of loop unrolling. Higher unrolling amounts lead to higher
// performance but also greater resource usage.
#ifndef UNROLL
#define UNROLL 20
#endif

// Define the color black as 0
#define BLACK 0x00000000

////////////////////////////////////////////////////////////////////
// Hardware implementation of the mandelbrot algorithm
////////////////////////////////////////////////////////////////////
__kernel 
void hw_mandelbrot_frame (
              const double x0,
							const double y0,
							const double stepSize,
							const unsigned int maxIterations,
							__global unsigned int *restrict framebuffer,
							__constant const unsigned int *restrict colorLUT,
							const unsigned int windowWidth)
{
	// Work-item position
	const size_t windowPosX = get_global_id(0);
	const size_t windowPosY = get_global_id(1);
	const double stepPosX = x0 + (windowPosX * stepSize);
	const double stepPosY = y0 - (windowPosY * stepSize);

	// Variables for the calculation
	double x = 0.0;
	double y = 0.0;
	double xSqr = 0.0;
	double ySqr = 0.0;
	unsigned int iterations = 0;

	// Perform up to the maximum number of iterations to solve
	// the current work-item's position in the image
  //
  // The loop unrolling factor can be adjusted based on the amount of FPGA
  // resources available.
  #pragma unroll UNROLL
	while (	xSqr + ySqr < 4.0 &&
			iterations < maxIterations)
	{
		// Perform the current iteration
		xSqr = x*x;
		ySqr = y*y;

		y = 2*x*y + stepPosY;
		x = xSqr - ySqr + stepPosX;

		// Increment iteration count
		iterations++;
	}

	// Output black if we never finished, and a color from the look up table otherwise
	framebuffer[windowWidth * windowPosY + windowPosX] = (iterations == maxIterations)? BLACK : colorLUT[iterations];
}
```

**Comment by Jiefei-Wang** [comment]
Hi,

It looks like your function defines the arguments as scalar values except for the last one
```
kernel void mandelbrotOpenCL(global float fromX, global float toX, 
                             global float fromY, global float toY,
                             global int width, global int height,
                             global int maxiter,
                             global int* res)
```
Please note that the OpenCL function only accepts the pointer as the argument, that is the main reason you obtain the error. To fix the error, you should define the arguments as pointers(like your last argument). 

I also noticed that you use `get_global_id(1)`. This is not supported by the package, you should always use `get_global_id(0)`.  The number of iterations should be specified in `.globalThreadNum`.

------------------------------------------------------------------------------------------------------------
Meanwhile, since you are using `gpuMagic`, why not take advantage of the package? You can actually use R function to do your calculation. Certain restrictions apply so you need to a little change to your code.
```
myfun <- function(i, fromX, toX, fromY, toY, width, height, maxiter){
  py = floor(i/width)
  px = i - width * py
  
  iteration = -1
  if(px < width) {
    if(py < height){
      x0 = fromX + px * (toX - fromX) / width
      y0 = fromY + py * (toY - fromY) / height
      x = 0
      y = 0
      for (iteration in 0:(maxiter-1)) {
        xn = x * x - y * y + x0;
        y = 2 * x * y + y0;
        x = xn;
        if (x * x + y * y > 4.0) {
          break;
        }
      }
    }
  }
  return(iteration)
}

res <- gpuSapply(1:(width*height), myfun, fromX, toX, fromY, toY, width, height, maxiter)
```
This gives
```
> head(res)
[1] 452 452 452 452 452 452
```

Since your function only computes one element in the matrix in each iteration, the result will be a vector. All you need to do it to convert it back into a matrix at the end.

Disclaimer: I do not know the correct answer for your code so my code might be wrong, you can use it as a starter, but do not 100% trust my code.

A quick start guide can be found in [here](https://www.bioconductor.org/packages/release/bioc/vignettes/gpuMagic/inst/doc/Quick_start_guide.html)


-----------------------
> Also, I was wondering what is the correct way to pass vectors and scalars? And constant scalars, like maxiter in this case, which I would like to be a const? Right now everything would seem to be passed as matrices, which somehow doesn't feel right

In fact, you do not have to create a `gpuMatrix` object as an argument. For example

```
code='
kernel void mandelbrotOpenCL(global double* x) {
    printf("%f\\n",*x);
    
}
'

x = 10
.kernel(src = code, 
        kernel='mandelbrotOpenCL',
        parms=list(x),
        .globalThreadNum = 1,
        .options = options)
```
Will print `10` to the R console. However, in this case, you can only create an argument of the `double *` type(Even if the variable is of integer type in R).



Please let me know if you have more questions

**Comment by tomwenseleers** [comment]
Many thanks! That's very helpful! I managed to get the R function compiled to OpenCL using gpuMagic working - see below for some timings & a comparison to some timings with an Rcpp OpenMP and and OpenMP+SIMD version. Based on OpenCL timings I saw elsewhere I was sort of hoping I would be able to beat my Rcpp versions (https://github.com/tomwenseleers/mandelExplorer), but apparently that's not the case - the GPU version is still 2-9x slower on my 16 core Intel i9 laptop with an NVIDIA RTX A2000 Laptop GPU than the multithreaded Rcpp versions - but pretty good nevertheless, as I get a 169x speed increase of the GPU version compared to the pure R version! Could perhaps be nice to include a slightly more complex example like this one in the help file or vignette...

I don't know if some performance benefit could still be had by doing the compilation to OpenCL using `compileGPUCode `beforehand, and then trying to call that using `.kernel`? Would that be possible and would that give a performance benefit? E.g. if I wanted to call my OpenCL function repeatedly, but just using different values for `fromX`, `toX`, `fromY `and `toY`, without wasting any time on repeated compilation of the same R function? My own OpenCL function called using `.kernel` I didn't manage to get working - I made the changes you proposed above, but I am still getting various compilation errors, e.g. error: invalid operands to binary expression ('long' and '__global int *') float x0 = fromX + px * (toX - fromX) / width;. But since `compileGPUCode()$gpu_code` can produce working OpenCL code I suppose there should not be any benefit of trying to call OpenCL code directly here? Except perhaps by some savings in R to OpenCL compile time? What do you think?

I was also wondering if it is possible to have the generated OpenCL code work with float instead of double and with uint instead of int, and if so, if that could also result in speed improvements?

```
library(gpuMagic)
library(compiler)
enableJIT(3)

getDeviceList()
setDevice(1)

fromX = -0.74877 
toX = -0.74872
fromY = 0.065053 
toY = 0.065103 
width = 1080L
height = 1080L
maxiter = 10000L;
# colour palette
library(RColorBrewer)
cols =  c(colorRampPalette(rev(RColorBrewer::brewer.pal(11, "RdYlBu")))(100), 
   colorRampPalette(RColorBrewer::brewer.pal(11, "RdYlBu"))(100), 
          "black") 

# define pure R Mandelbrot function to compile to OpenCL GPU version using gpuMagic
mandelbrotfun <- function(i, fromX, toX, fromY, toY, width, height, maxiter){
  py = 1+floor((i-1)/width) # Y pixel, 1...height
  px = 1+((i-1) - width * floor((i-1) / width)) # = 1+(i-1) %% width = X pixel, 1...width
  
  iteration = -1
  x0 = fromX + px * (toX - fromX) / width
  y0 = fromY + py * (toY - fromY) / height
  x = 0
  y = 0
  for (iteration in 0:(maxiter-1)) {
        xn = x * x - y * y + x0;
        y = 2 * x * y + y0;
        x = xn;
        if (x * x + y * y > 4.0) {
          break;
        }
  }
  return(iteration)
}
```

Timings of the CPU pure R version on my 16 core 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz :
```
system.time(res <- sapply(1:(width*height), mandelbrotfun, 
                          fromX, toX, fromY, toY, width, height, maxiter))

# 120s
m <- matrix(res, nrow=width)
par(mar=c(0, 0, 0, 0))
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 
```

![mandelbrot](https://user-images.githubusercontent.com/12063422/210641712-7397cb50-4955-41dd-8302-59aaa6cc8587.png)

Timings of the GPU OpenCL version (on NVIDIA RTX A2000 Laptop GPU) :  169x faster than the CPU pure R version
```
# warmup, first time it is called timing is always a little longer due to R to OpenCl compilation time
# doing warmup with a low res render
res <- gpuSapply(1:(10L*10L), 
                 mandelbrotfun, 
                 fromX, toX, fromY, toY, 10L, 10L, maxiter) 
system.time(res <- gpuSapply(1:(width*height), 
                             mandelbrotfun, 
                             fromX, toX, fromY, toY, width, height, maxiter))
# 0.71s, for options see gpuSapply.getOption()
m <- matrix(res, nrow=width)
par(mar=c(0, 0, 0, 0))
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 
# 0.40s
# PS much faster option to display raster is using a native raster, 
# https://github.com/coolbutuseless/nara
```

Timings of two Rcpp versions I made :
```
library(remotes)
remotes::install_github('tomwenseleers/mandelExplorer', update='none')
library(mandelExplorer)
library(microbenchmark)   
```

Rcpp OpenMP version, https://github.com/tomwenseleers/mandelExplorer/blob/main/src/mandelRcpp.cpp :
2x faster than the GPU version on my 16 core 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz :
```
microbenchmark(m <- mandelRcpp(fromX, toX, 
                               fromY, toY, 
                               width, 
                               height, maxiter), unit="s") # 0.36s
par(mar=c(0, 0, 0, 0))
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 
```

Rcpp OpenMP version using vectorized SIMD intrinsics, https://github.com/tomwenseleers/mandelExplorer/blob/main/src/mandelRcpp.cpp :
9x faster than the GPU version on my 16 core 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz :
```
microbenchmark(m <- matrix(mandelRcpp2(fromX, toX, 
                                       fromY, toY, 
                                       width, 
                                       height, maxiter), 
                           nrow=width),
               unit="s") # 0.077s
m[m==0] <- maxiter
m <- matrix(m, nrow=width)
par(mar=c(0, 0, 0, 0))
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 
```

**Comment by Jiefei-Wang** [comment]
Wow, thanks for sharing this amazing figure!

`gpuSapply` uses `compileGPUCode` and `.kernel` to do all the dirty work for you, so there will be no performance benefit from manually doing it. However, you might find it helpful by looking at the OpenCL code generated by `compileGPUCode` and then using it to write your own OpenCL code. The output code is a little bit verbose but I believe it is still understandable(I remember I spent a lot of time improving its readability)

Meanwhile, the R function `mandelbrotfun` will only be compiled by `compileGPUCode` once. In your performance comparison, please give `gpuSapply` a warm-up by calling it with a simple task. The subsequent call will use the compiled GPU code.

As for the performance, two things to notice:
1. GPU operation is kind of "heavy", so if the load is not large you will not see much improvement over CPU. Imaging you are comparing the cargo transport speed of a sedan and a truck. If all you need is to ship a small laptop, choosing a truck will only make the shipping time longer. In our case, the CPU is the sedan and GPU is the truck.
2. We can definitely use `float` type instead of `double` to improve the speed, you can do this by
```
gpuMagic.setOptions(default.float = "float")
```
Most GPU is significantly fast on float-type computation. The default is `double` only because we want to be consistent with R's precision.

----------------
After changing the precision to `float` and increasing the canvas size, here is my benchmark on 12-core Ryzen 9 3900X and RTX 3070TI
```
width = 1024L*8L
height = 1024L*8L
gpuMagic.setOptions(default.float = "float")
system.time(res1 <- gpuSapply(1:(width*height), 
                             mandelbrotfun, 
                             fromX, toX, fromY, toY, width, height, maxiter))
# 1.3s with gpuMagic.setOptions(default.float = "float")

system.time(res2 <- matrix(mandelRcpp2(fromX, toX, 
                                         fromY, toY, 
                                         width, 
                                         height, maxiter), 
                             nrow=width)) 
# 3.16s
```
I guess that's the best result you can get without knowing the details of GPU structure. Further improvement will require writing raw OpenCl code and finding the bottleneck of the code.  Please let me know if you need further assist.

**Comment by tomwenseleers** [comment]
Many thanks - that's clear! Really cool that for larger problem sizes and when using float it actually becomes faster than my Rcpp OpenMP+SIMD (double) version! The timing I had given was already using a warmup, as I noticed it was slightly slower the very first time you called it - nice that it remembers the compiled code.

Timing for gpuMagic.setOptions(default.float = "float") and using width & height of 1080L as in my code above gave me a timing of 0.09s, so that's almost competitive with my Rcpp OpenMP+SIMD (double) version & 1333x faster than the pure R code (with the speed benefit being even larger for larger problem sizes with larger width & height).
Working with float will of course mean one can zoom in less before hitting the limit of numerical accuracy (a zoom of x10^5 is the max then vs x10^12 when using double). Deep zooms, like this one, [https://www.youtube.com/watch?v=pCpLWbHVNhk,](https://www.youtube.com/watch?v=pCpLWbHVNhk), which zooms by a factor of x10^1091 (making the complete Mandelbrot fractal many orders of magnitude larger than the visible universe at final magnification), requires the use of special perturbation methods and some arbitrary precision math, as implemented e.g. in [https://gbillotey.github.io/Fractalshades-doc/overview.html](https://gbillotey.github.io/Fractalshades-doc/overview.html)).

If you like the example feel free to include it in the help file or vignette! Calculating a Mandelbrot fractal is one of those typical benchmarks & a great example where OpenCL GPU code tends to perform very well, as it is so highly parallelizable. 
Plus you get pretty pictures with very little code!

Anyway, will close this question now! Thank you for your help & your work on this cool package!

**Comment by Jiefei-Wang** [comment]
Just for fun, handwriting the OpenCL code will give you 4X more performance benefits compared with the auto-generated code. Humans still can prove their value!

```
library(gpuMagic)
code='
kernel void mandelbrotOpenCL(global int* res, 
          global double* width, global double* height, 
          global double* fromX, global double * fromY, global double* toX, global double* toY) {
    int id = get_global_id(0);
    int px = fmod(id,height[0]);
    int py = id /((int) height[0]);
    int iteration;
    float x0 = fromX[0] + px * (toX[0] - fromX[0]) / width[0];
    float y0 = fromY[0] + py * (toY[0] - fromY[0]) / height[0];
    float x = 0;
    float y = 0;
    for (iteration = 0; iteration < 10000; iteration++) {
      float xn = x * x - y * y + x0;
      y = 2 * x * y + y0;
      x = xn;
      if (x * x + y * y > 4.0) {
        break;
      }
    }
    res[(uint)(width[0] *py  + px)] = iteration;
}
'


# Create data in R
res_dev = gpuEmptMatrix(height, width, type='int')
fromX = -0.74877 
toX = -0.74872
fromY = 0.065053 
toY = 0.065103 
width = 1024*8
height = 1024*8

system.time(
  {
    .kernel(src = code, 
            kernel='mandelbrotOpenCL',
            parms=list(res_dev, width, height, fromX, fromY, toX, toY),
            .globalThreadNum = width*height)
    
    res_dev=download(res_dev)
    res=as.matrix(res_dev)
  }
)
# 0.39s on RTX 3070 TI
```

**Comment by tomwenseleers** [comment]
Ha cool - many thanks for that - then I have a nice example of manually written OpenCL code as well! 
How would one pass a const for `maxiter` of 10000, instead of hardcoding it (passing it as an additional `global int* maxiter` and replacing `iteration < 10000` by `iteration < maxiter` seems to make things super slow, and adding a parameter `constant int* maxiter` crashes when I then try res_dev <- download(res_dev))? Or put MAXITER in my code_float and then use code_float2  <- gsub("MAXITER", as.character(maxiter), code_float) or something like that (a bit of an ugly solution though)?

What was the critical change in the manually written code vs the R OpenCL compiled code you reckon?

Had to slightly change your definition of `px `and `py `and `x0 `and `y0 `to get it work correctly though (ChatGPT gave me some helpful debugging advice :-) - some printf()s did the trick) - here is the timings on my machine, for `width` and `height = 1080L` and for a `float `and a `double `version - it's mainly the `float `version that is very fast :

```
# OpenCL Mandelbrot code using float #### 
# 3x faster than Rcpp OpenMP+SIMD double version, 4444x faster than pure R version, but float instead of double
code_float='
kernel void mandelbrotOpenCL(global int* res, 
          global double* width, global double* height, 
          global double* fromX, global double* toX, 
          global double* fromY, global double* toY) {
    int id = get_global_id(0);
    int px = id % ((int) width[0]);
    int py = id / ((int) width[0]);
    int iteration;
    float x0 = fromX[0] + ((double)px) * (toX[0] - fromX[0]) / width[0];
    float y0 = fromY[0] + ((double)py) * (toY[0] - fromY[0]) / height[0];
    float x = 0;
    float y = 0;
    for (iteration = 0; iteration < 10000; iteration++) {
      float xn = x * x - y * y + x0;
      y = 2 * x * y + y0;
      x = xn;
      if (x * x + y * y > 4.0) {
        break;
      }
    }
    res[(uint)(width[0] *py  + px)] = iteration;
}
'

res_dev = gpuEmptMatrix(height, width, type='int')

microbenchmark(
  {
    .kernel(src = code_float, 
            kernel='mandelbrotOpenCL',
            parms=list(res_dev, width, height, fromX, toX, fromY, toY),
            .globalThreadNum = width*height)
    res_dev <- download(res_dev)
    m <- matrix(res_dev, nrow=width)
  }, unit="s")
# 0.027s on NVIDIA RTX A2000 Laptop GPU
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 


# OpenCL Mandelbrot code using double #### 
# similar speed than Rcpp OpenMP non-SIMD version, 400x faster than pure R version
code_double='
kernel void mandelbrotOpenCL(global int* res, 
          global double* width, global double* height, 
          global double* fromX, global double* toX, 
          global double* fromY, global double* toY) {
    int id = get_global_id(0);
    int px = id % ((int) width[0]);
    int py = id / ((int) width[0]);
    int iteration;
    double x0 = fromX[0] + ((double)px) * (toX[0] - fromX[0]) / width[0];
    double y0 = fromY[0] + ((double)py) * (toY[0] - fromY[0]) / height[0];
    double x = 0;
    double y = 0;
    for (iteration = 0; iteration < 10000; iteration++) {
      double xn = x * x - y * y + x0;
      y = 2 * x * y + y0;
      x = xn;
      if (x * x + y * y > 4.0) {
        break;
      }
    }
    res[(uint)(width[0] *py  + px)] = iteration;
}
'

res_dev = gpuEmptMatrix(height, width, type='int')

microbenchmark(
  {
    .kernel(src = code_double, 
            kernel='mandelbrotOpenCL',
            parms=list(res_dev, width, height, fromX, toX, fromY, toY),
            .globalThreadNum = width*height)
    res_dev <- download(res_dev)
    m <- matrix(res_dev, nrow=width)
  }, unit="s")
# 0.30s on NVIDIA RTX A2000 Laptop GPU
system.time(image(m^(1/3), col=cols, asp=(toY-fromY)/(toX-fromX), axes=F, useRaster=T)) 
```

**Comment by Jiefei-Wang** [comment]
Thanks for the debugging. 

Please note that all arguments in OpenCL code are of `double *` type unless you create the argument in R by `gpuMatrix`(for example, the argument `res`). So you should declare the argument `maxiter` as `global double *`. 

The only trick I make here is that I use the local memory to do the computation in the for loop instead of the global memory. The local memory is like the CPU's L1 cache. It is very fast, so GPU does not need to wait for the data from the global memory. We as R programmers do not care about the location of our data as we know the CPU will handle them. However, the GPU is very stupid and you must explicitly tell it where you want your data to be. 

Given the context above, the only reason I hardcoded `maxiter` is that I'm not sure if the GPU will read `maxiter` from the global memory(we need `maxiter`  to determine if it is the end of the loop in each iteration), so I skip it in my code for simplicity. After playing with it today, the answer is yes. Putting `maxiter` inside the for loop will slow the program down. Therefore, we need to create a temporary variable to hold the value of `maxiter`. 

Here is the updated version with `maxiter` as an argument
```
kernel void mandelbrotOpenCL(global int* res, 
          global double* width, global double* height, 
          global double* fromX, global double* toX, 
          global double* fromY, global double* toY, global double* maxiter) {
    int id = get_global_id(0);
    int px = id % ((int) width[0]);
    int py = id / ((int) width[0]);
    int iteration;
    float x0 = fromX[0] + ((double)px) * (toX[0] - fromX[0]) / width[0];
    float y0 = fromY[0] + ((double)py) * (toY[0] - fromY[0]) / height[0];
    float x = 0;
    float y = 0;
    uint n = maxiter[0];
    for (iteration = 0; iteration < n; iteration++) {
      float xn = x * x - y * y + x0;
      y = 2 * x * y + y0;
      x = xn;
      if (x * x + y * y > 4.0) {
        break;
      }
    }
    res[(uint)(width[0] *py  + px)] = iteration;
}
```


The performance differences between double and float versions are expected. Because GPU is (mostly) designed for gaming. Games do not need accuracy. From Nvidia's specification, your GPU double-to-float ratio is 1:64, which means it is capable to compute float 64X faster than double. Our observed ratio is 1:10, which may indicate room for more optimization. Vectorization might be an option(Yes, OpenCL has vector operation), but I do not know how much juice you can get here. I'm not an OpenCL expert as well, so if you really want to squash all juice from GPU you might need to ask this question in an OpenCL forum.

**Comment by tomwenseleers** [comment]
Many thanks for that - that did the trick!
